meshcloud/collie-cli

src/commands/tenant.command.ts

fix(cli) fix collie completions

---

src/aws/aws-mesh-adapter.ts
src/azure/auto-install-azure-cli-module-decorator.ts
src/azure/azure-cli-facade.ts
src/azure/azure-mesh-adapter.ts
src/azure/azure.model.ts
src/azure/basic-azure-cli-facade.ts
src/azure/retrying-azure-cli-facade-decorator.ts
src/commands/config.command.ts
src/commands/tenant.command.ts
src/config/config.model.ts
src/mesh/mesh-tenant.model.ts

By manually setting up a parent management group id, the cost query can be
done much faster.
This PR adds this modified query (fallback to old query) as well as a possibility
to configure the parent management group.

feat: Azure cost query performance improvements

---

src/aws/aws-cli-facade.ts
src/azure/auto-install-azure-cli-module-decorator.ts
src/azure/azure-cli-facade.ts
src/azure/azure-mesh-adapter.ts
src/azure/basic-azure-cli-facade.test.ts
src/azure/basic-azure-cli-facade.ts
src/azure/retrying-azure-cli-facade-decorator.ts
src/dev-deps.ts
src/errors.ts
src/gcp/gcp-cli-facade.ts

Skips Subscritpions which are not collectible via the Azure Consumption API.

fix: Does not fail anymore on non collectible cost info for Azure

---

src/aws/aws-cli-facade.ts
src/azure/basic-azure-cli-facade.ts
src/commands/config.command.ts
src/config/config.model.ts
src/db/mesh-tenant-repository.ts
src/gcp/gcp-cli-facade.ts
src/init.ts
src/json.ts
src/main.ts
src/presentation/tabel-view.model.ts

Collie will now display errors even then thrown in the setup phase.
Unifies stacktrace display for easier debugging.
Removes certain earlier exists and let the error handling in `main.ts` do the work. Switched some error logs in favor of Exceptions.

feat: Improves error message handling

---

src/commands/tty.ts
src/presentation/tabel-view.model.ts
src/process/loader-shell-runner.ts

Fixes the problem of tty cursor staying invisible after the user send SIGINT to the running programm.
Also slightly improves tty detection and writes TTY commands in sync to avoid resource in use problems.

fix: Cursor stying hidden after SIGTERM or SIGINT

---

src/aws/aws-mesh-adapter.ts
src/azure/azure-mesh-adapter.ts
src/presentation/csv-tenant-usage-presenter.ts
src/presentation/json-presenter.ts
src/presentation/table-tenant-usage-presenter.ts

Tenant cost collection for AWS and Azure is now also collecting the currency symbol.

feat: Collects currency symbol

---

.github/README.md
src/commands/config.command.ts

fix: Collie config no longer crashes

---

.github/README.md

* And removed GitOps section, which is not supported yet.

feat: Add tutorial links directly in README.

---

src/aws/aws-cli-facade.test.ts
src/aws/aws-mesh-adapter.ts
src/azure/azure-mesh-adapter.ts
src/mesh/caching-mesh-adapter-decorator.ts
src/mesh/mesh-tenant.model.ts
src/presentation/csv-tenant-usage-presenter.ts
src/presentation/json-presenter.ts
src/presentation/meshtenantcost-table-view-generator.ts
src/presentation/tenant-usage-presenter-factory.ts

* Renamed totalUsageCost to cost so it takes less space
* Fixed an issue with retrieving cached tenants.
* Fixed table only showing one month per tenant at maximum (closes #51)
Found these when creating screenshots for the website

feat: Smaller Improvements

---

src/aws/aws-cli-facade.ts
src/azure/basic-azure-cli-facade.ts
src/gcp/gcp-cli-facade.ts

- first suggest how to fix with the native cli command
- then suggest how to disconnect collie

feat: harmonize error message when cli not authenticated

---

src/gcp/gcp-mesh-adapter.ts

fix: handle GCP projects with empty IAM policies

---

src/process/loader-shell-runner.ts

Improves the spinner animation termination to avoid part of the error message
writing into the spinner animation text.
Fixes #82

fix: Spinner animation overwrites error message

---

src/aws/aws-mesh-adapter.ts
src/azure/azure-mesh-adapter.ts
src/commands/tenant.command.ts
src/mesh/mesh-tenant.model.ts
src/presentation/config-table-view-generator.ts
src/presentation/json-presenter.ts
src/presentation/mesh-table.ts
src/presentation/meshtenant-iam-table-view.ts
src/presentation/meshtenant-table-view-generator.ts
src/presentation/meshtenantcost-table-view-generator.ts
src/presentation/tenant-usage-presenter-factory.ts

Example output:
```
┌────────────────────────────────────────────────┬────────────────┬──────────┬────────────┬────────────┬────────────────────────────────────────────────────────────┐
│ relatedTenant                                  │ cost           │ currency │ from       │ to         │ tags                                                       │
├────────────────────────────────────────────────┼────────────────┼──────────┼────────────┼────────────┼────────────────────────────────────────────────────────────┤
│ (AWS) managed-customer.test-js-10-dev          │ 0              │          │ 2021-06-01 │ 2021-07-01 │ meshstack_pident:       prefix-test-js-10-dev              │
│                                                │                │          │            │            │ …
```

feat: Tags are shown in table cost view

---

src/mesh/caching-mesh-adapter-decorator.ts

Went a bit overboard here the last time. This is undoing a change from a while ago.

fix: Fix costs / IAM missing in cached tenants.

---

src/aws/aws-cli-facade.ts
src/aws/aws-mesh-adapter.ts
src/azure/azure-mesh-adapter.ts
src/azure/basic-azure-cli-facade.ts
src/azure/retrying-azure-cli-facade-decorator.ts
src/cli-detector.ts
src/commands/cache.command.ts
src/commands/config.command.ts
src/db/mesh-tenant-repository.ts
src/deps.ts
src/gcp/gcp-cli-facade.ts
src/gcp/gcp-mesh-adapter.ts
src/init.ts
src/json.ts
src/logger.ts
src/main.ts
src/mesh/caching-mesh-adapter-decorator.ts
src/mesh/query-statistics.ts
src/mesh/time-window-calculator.ts
src/process/shell-runner.ts

Changes log handling so the blue debug message color is gone which improves
readability in Windows Powershell.

feat: Improve readability for debug messages on Windows

---

src/aws/aws-shell-runner.ts

fix: Allows env to override AWS access tokens

---

.github/workflows/build.yml
src/config/cache-config-manager.ts
src/deps.ts
src/process/loader-shell-runner.test.ts
src/process/loader-shell-runner.ts

this contains a breaking change in the unstable signal handler API

chore: upgrade to deno 1.16

---

.github/workflows/build.yml
.github/workflows/releases.yml
CONTRIBUTING.md
default.nix
src/dev-deps.ts
src/mesh/query-statistics.test.ts
src/mesh/query-statistics.ts

Switch to main branch only development

---

.githooks/pre-commit
CONTRIBUTING.md

see contributing.md for usage instructions

chore: add fmt githook

---

src/info.ts

release v0.14.1

---

src/commands/kit/bundle.command.ts

also removing some other dependencies from bundle command shaves about 30ms of (warm) startup time for a collie invocation without commands, from about 250ms to 220ms on my MBP2018

fix: ioctl errors on latest deno versions caused by a dependency

---

src/api/git/GitCliFacade.ts
src/commands/init.command.ts

https://github.com/meshcloud/collie-hub/pull/39

feat: collie init creates dir

---

src/commands/foundation/docs.command.ts

this allows just running the static site generator without launching preview. This is useful for e2e tests

feat: add a --build switch to foundation docs

---

.github/workflows/release.yml

https://github.com/meshcloud/collie-cli/actions/runs/6311668479/job/17136129448

chore: add macos e2e test

---

src/cli/commandOptionsConventions.ts

feat: skip selecting foundations if repo only has a single one

---

src/main.ts

this is consistent with the behavior of terraform/terragrunt

feat: force collie to exit when receiving second interrupt from user
