src/aws/aws-cli-facade.ts, src/commands/config.command.ts, src/errors.ts
Improves detection if a users from a non management account is used to with Collie.
A management account user is required to properly list org accounts.
=> feat: Improves AWS error message regarding permissions

src/commands/cache.command.ts
=> fix: `collie cache` will show help

src/commands/tenant.command.ts, src/init.ts, src/process/shell-runner.ts
In order to optimize startup time, especially when only issuing a non
cloud-cli required command, collie now only checks cloud cli configuration
when required.
Should mitigate or at least lessens @JohannesRudolph startup time issue.
=> feat: Avoid cli setup checks when not required

src/aws/aws-cli-facade.ts, src/azure/basic-azure-cli-facade.ts, src/commands/config.command.ts, src/gcp/gcp-cli-facade.ts, src/json.ts
This ensures that there is always either a `stderr` or `stdout` printed. It happens a lot where an error is thrown that is not caught, and the `stdout` is empty in the end. The `stderr` then gets lost.
=> feat: Improved JSON parsing so it always logs a message

src/azure/basic-azure-cli-facade.ts
fixes #76
I wonder though if a better fix would be to change the `ShellRunner` interface to take a `string[]` for commands instead of the somewhat dangerous `cmdString.split(" ")` in there?
=> fix: use azure subscription id instead of name to prevent word-splitting

src/process/loader-shell-runner.ts
Prevents the text overflowing problem and constant tty writing if the window
is too small to hold the whole text.
=> fix: Truncates loader string on small TTY

src/main.ts, src/process/loader-shell-runner.ts
Supresses error messages from failed JSON parsing when a
SIGINT or SIGTERM was send to the clouds cli child processes.
fix #81
=> fix: Does not print error msg when SIGTERM or SIGINT

.github/workflows/releases.yml
Avoids the change of history by modifying the release workflow.
Its now necessary to insert the new release tag via a git commit locally before pushing this tag than to the `develop` branch. This will trigger a release.
=> chore: Improves release workflow

src/api/aws/AwsMeshAdapter.ts, src/api/az/AzMeshAdapter.ts, src/api/gcloud/GcloudMeshAdapter.ts, src/mesh/MeshTenantModel.ts, src/presentation/json-presenter.ts
now using ISO date strings in our models as that simplifies handling
serialization/deserialization when collie cache is involved
=> fix: date serialization issue in tenant cost command json output

src/api/CliApiFacadeFactory.ts, src/api/git/GitCliDetector.ts, src/api/git/GitCliFacade.ts, src/commands/init.command.ts
as long as we use presence of .git to detect a collie repo, we should also ensure that collie init creates git repos
closes #165
=> feat: collie init ensures an initialized git repo

src/FirstTimeExperience.ts, src/commands/FoundationType.ts, src/commands/foundation/config.command.ts, src/commands/foundation/deploy.command.ts, src/commands/foundation/docs.command.ts, src/commands/foundation/new.command.ts, src/commands/interactive/interactive.command.ts, src/commands/tenant/prepareTenantCommand.ts, src/model/CollieRepository.ts
always traverse the path to the nearest collie repository root for all commands except "collie init"
=> feat: support running collie commands from subdirectories of repo

build.sh, install.sh
I needed to support Apple silicon so we could install collie-cli on our company's laptops.
This PR simply adds support in install.sh and build.sh for both CPU architectures available with MacOSX.
As a side note it will require a github release to fully work with arm64 since we need an valid artifact in there.
=> feat: add support for Apple Silicon at build and install time

.github/workflows/build.yml, .github/workflows/release.yml, CONTRIBUTING.md, build.sh, default.nix, src/info.ts
- run deno check and deno test in build workflow
- leave deno compile to the release workflow (we generally trust deno compile to not break if deno check passed)
- get rid of manually bumping version in info.ts
this should make it much smoother to create new collie releases
=> chore: simplify the release process

src/commands/kit/kit-utilities.ts
This fixes collie kit apply
```
Error: Create local file error
│
│   with local_file.output_md,
│   on documentation.tf line 6, in resource "local_file" "output_md":
│    6: resource "local_file" "output_md" {
│
│ An unexpected error occurred while writing the file
│
│ +Original Error: open : no such file or directory
╵
```
=> fix: kit apply must not generate output-md-file

src/commands/info.command.ts, src/commands/version.command.ts, src/main.ts
This command now returns runtime and detected CLI version infos. The version command now outputs only the version number
=> feat: add a collie info command

src/commands/info.command.ts
this improves clarity about installed/not installed dependencies
=> feat: add red/green icons to collie info

.github/README.md
shorten what's on the readme to keep it tech-focused and move everything else into collie-hub
=> docs: align collie readme with collie-hub

install.ps1
When Collie was already installed on the machine, the install script did not clean up the old version. This scenario only worked when the installed version matches the latest version on GitHub. For example I had 0.7.0 installed but it didn't find that directory and clean it up from the file system and PATH.
I instead changed the installation to be version independent so we don't have to magically check for all possible installed versions but we just replace whatever Collie executable is there.
=> fix: Powershell upgrade scenario not workign

src/commands/kit/compile.command.ts
like when a required cli tool was not installed.
changed error handling to always log errors and also provide context (which module failed validation)
i messed this up against better judgement (catch alls always suck...)
=> fix: kit compile could swallow unexpected errors

src/commands/init.command.ts
collie cli's code generation emits LF endings and a lot of the parsing code e.g. for yaml frontmatter expects this as well
also, we're switching collie hub to LF endings as well https://github.com/meshcloud/collie-hub/pull/63
=> feat: configure collie repo with LF line endings

src/main.ts, src/process/TransparentProcessRunner.ts
this fixes a bug where collie would exit first and yield back to the shell and subprocesses like terragrunt would continue writing their output to
=> fix: when exiting collie via SIGTERM or SIGINT wait for subprocesses

default.nix
az cli is currently broken on nix-unstable, workaround this by using provider cli's from stable and terraform etc. from unstable
=> chore: upgrade default.nix

deno.lock, src/api/aws/AwsCliDetector.ts, src/api/az/AzCliDetector.ts, src/api/gcloud/GcloudCliDetector.ts, src/api/git/GitCliDetector.ts, src/api/npm/NpmCliDetector.test.ts, src/api/npm/NpmCliDetector.ts, src/api/terraform-docs/TerraformDocsCliDetector.ts, src/api/terraform/TerraformCliDetector.ts, src/api/terragrunt/TerragruntCliDetector.ts, src/import_map.json
switch cli version detection to use proper semver parsing and constraint evaluation
=> fix: correctly detect npm 10 as supported

src/commands/kit/kit-utilities.ts
We have stopped including separate module.hcl in bootstrap modules on collie hub
While the idea of DRY'ing provider configuration across multiple modules is good in theory,
it adds another layer of learning curve and also gets in the way for more complex kit modules that need to 
work with multiple provider instances (e.g. on multiple AWS Accounts etc.)
=> Remove module.hcl from fallback templates generated by "kit apply"

src/commands/foundation/new.command.ts
this allows running foundation new in e2e tests or automation
=> fix: "foundation new" should not prompt when stdout is not a tty

src/main.ts
windows only supports SIGINT and SIGBREAK
=> fix: crash on windows due to invalid signal

src/commands/foundation/docs.command.ts
This makes collie behave consistently on windows and linux. Before we could do "foundation docs --build" on linux but on windows we needed "foundation docs --build true".
=> feat: pass --preview and --build as simple flags to foundation docs

src/commands/kit/apply.command.ts, src/commands/kit/kit-utilities.ts, src/compliance/ComplianceControlParser.test.ts, src/compliance/ComplianceControlParser.ts, src/docs/DocumentationRepository.ts, src/foundation/FoundationDependenciesTreeBuilder.ts, src/kit/KitModuleParser.ts, src/path.ts
=> fix: consistently use posix paths for links generated in docs markdown

src/cli/validation.test.ts, src/cli/validation.ts, src/commands/compliance/new.command.ts, src/commands/kit/new.command.ts
collie's repository layout assumes the following pattern
- controls are prefixed framework/control
- kit modules are prefixed platform/module
this implicit assumption is in place for the "tree" commands and we think its a good convention for consistency
fixes #262
=> feat: add validation to verify control and kit module ids in "new"

src/commands/kit/kit-utilities.ts
thats missing if you would use it with our workflow and its also part of all our terragrunt.hcl in the kits
=> chore: adding expose=true collie kit apply

src/foundation/PlatformDeployer.ts
the previous implementation had a bug where setting the --module
flag would subsequently not find the module to invoke
=> fix: "detected no test modules" error in "foundation test --module"
